use_default_settings: true

server:
  secret_key: "changeme"
  image_proxy: true

search:
  formats:
    - html
    - json

botdetection:
  enabled: false

engines:
  - name: bing
    engine: bing
    shortcut: b
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false

  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false
