"""Centralized Board Registry (src/radar/board_registry.py)

Single authoritative source for verified company ATS boards and portals.
Includes FAANG/Big Tech, Indian Unicorns, HFTs, AI Labs, DevTools, Cloud,
Fintech, Biotech, Cybersecurity, and Remote-First hubs.
"""

from __future__ import annotations

import asyncio
from typing import Any

import httpx

from src.http_client import get_client
from src.logging import get_logger

logger = get_logger("board_registry")

# Master Registry of Verified Seed Boards & Career Portals (284+ tracked company endpoints)
REGISTERED_BOARDS: list[tuple[str, str, str]] = [
    # ── 1. BIG TECH / FAANG & GLOBAL MNC INDIA HUBS ──────────────────────────
    (
        "google:careers",
        "https://www.google.com/about/careers/applications/jobs/results/",
        "discovery_index",
    ),
    (
        "microsoft:careers",
        "https://careers.microsoft.com/v2/global/en/home.html",
        "discovery_index",
    ),
    ("amazon:careers", "https://www.amazon.jobs/en/search.json", "discovery_index"),
    ("meta:careers", "https://www.metacareers.com/jobs", "discovery_index"),
    ("apple:careers", "https://jobs.apple.com/en-us/search", "discovery_index"),
    (
        "nvidia:careers",
        "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
        "discovery_index",
    ),
    ("intel:careers", "https://jobs.intel.com", "discovery_index"),
    ("ibm:careers", "https://www.ibm.com/careers", "discovery_index"),
    ("oracle:careers", "https://www.oracle.com/corporate/careers/", "discovery_index"),
    (
        "salesforce:careers",
        "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site",
        "discovery_index",
    ),
    ("cisco:careers", "https://jobs.cisco.com", "discovery_index"),
    ("adobe:careers", "https://www.adobe.com/careers.html", "discovery_index"),
    ("intuit:careers", "https://www.intuit.com/careers/", "discovery_index"),
    ("qualcomm:careers", "https://www.qualcomm.com/company/careers", "discovery_index"),
    ("samsung:careers", "https://www.samsung.com/in/aboutsamsung/careers/", "discovery_index"),
    ("goldmansachs:careers", "https://www.goldmansachs.com/careers/index.html", "discovery_index"),
    ("jpmorgan:careers", "https://careers.jpmorgan.com/global/en/home", "discovery_index"),
    ("dell:careers", "https://jobs.dell.com", "discovery_index"),
    ("hpe:careers", "https://careers.hpe.com", "discovery_index"),
    ("vmware:careers", "https://careers.vmware.com", "discovery_index"),
    ("servicenow:careers", "https://careers.servicenow.com", "discovery_index"),
    ("sap:careers", "https://jobs.sap.com", "discovery_index"),
    ("siemens:careers", "https://jobs.siemens.com", "discovery_index"),
    ("bosch:careers", "https://www.bosch.in/careers/", "discovery_index"),
    ("texasinstruments:careers", "https://careers.ti.com", "discovery_index"),
    ("broadcom:careers", "https://www.broadcom.com/careers", "discovery_index"),
    ("amd:careers", "https://careers.amd.com", "discovery_index"),
    ("arm:careers", "https://careers.arm.com", "discovery_index"),
    ("micron:careers", "https://micron.wd1.myworkdayjobs.com/External", "discovery_index"),
    ("westerndigital:careers", "https://jobs.westerndigital.com", "discovery_index"),
    ("seagate:careers", "https://jobs.seagate.com", "discovery_index"),
    ("juniper:careers", "https://careers.juniper.net", "discovery_index"),
    ("paloaltonetworks:careers", "https://jobs.paloaltonetworks.com", "discovery_index"),
    ("fortinet:careers", "https://www.fortinet.com/corporate/about-us/careers", "discovery_index"),
    ("checkpoint:careers", "https://www.checkpoint.com/careers/", "discovery_index"),
    ("f5:careers", "https://www.f5.com/company/careers", "discovery_index"),
    ("akamai:careers", "https://www.akamai.com/careers", "discovery_index"),
    ("citrix:careers", "https://www.citrix.com/careers/", "discovery_index"),
    ("autodesk:careers", "https://www.autodesk.com/careers", "discovery_index"),
    ("atlassian:careers", "https://www.atlassian.com/company/careers", "discovery_index"),
    ("workday:careers", "https://workday.wd5.myworkdayjobs.com/Workday", "discovery_index"),
    ("paypal:careers", "https://careers.pypl.com", "discovery_index"),
    ("ebay:careers", "https://careers.ebayinc.com", "discovery_index"),
    ("verizon:careers", "https://www.verizon.com/about/careers", "discovery_index"),
    ("att:careers", "https://www.att.jobs", "discovery_index"),
    ("ericsson:careers", "https://www.ericsson.com/en/careers", "discovery_index"),
    ("nokia:careers", "https://www.nokia.com/about-us/careers/", "discovery_index"),
    ("philips:careers", "https://www.philips.co.in/a-w/careers.html", "discovery_index"),
    ("ge:careers", "https://jobs.gecareers.com", "discovery_index"),
    ("honeywell:careers", "https://careers.honeywell.com", "discovery_index"),
    ("infosys:careers", "https://www.infosys.com/careers.html", "discovery_index"),
    ("tcs:careers", "https://ibegin.tcs.com/iBegin/", "discovery_index"),
    ("wipro:careers", "https://careers.wipro.com", "discovery_index"),
    ("hcltech:careers", "https://www.hcltech.com/careers", "discovery_index"),
    ("techmahindra:careers", "https://careers.techmahindra.com", "discovery_index"),
    ("cognizant:careers", "https://careers.cognizant.com", "discovery_index"),
    ("capgemini:careers", "https://www.capgemini.com/careers/", "discovery_index"),
    ("accenture:careers", "https://www.accenture.com/in-en/careers", "discovery_index"),
    ("deloitte:careers", "https://www2.deloitte.com/in/en/careers.html", "discovery_index"),
    ("pwc:careers", "https://www.pwc.in/careers.html", "discovery_index"),
    ("ey:careers", "https://www.ey.com/en_in/careers", "discovery_index"),
    ("kpmg:careers", "https://home.kpmg/in/en/home/careers.html", "discovery_index"),
    ("mckinsey:careers", "https://www.mckinsey.com/careers", "discovery_index"),
    ("bcg:careers", "https://careers.bcg.com", "discovery_index"),
    ("bain:careers", "https://www.bain.com/careers/", "discovery_index"),
    ("morganstanley:careers", "https://www.morganstanley.com/careers", "discovery_index"),
    ("barclays:careers", "https://search.jobs.barclays/", "discovery_index"),
    ("hsbc:careers", "https://www.hsbc.com/careers", "discovery_index"),
    ("deutschebank:careers", "https://careers.db.com", "discovery_index"),
    ("americanexpress:careers", "https://aexp.eightfold.ai/careers", "discovery_index"),
    ("visa:careers", "https://corporate.visa.com/en/jobs.html", "discovery_index"),
    ("mastercard:careers", "https://careers.mastercard.com", "discovery_index"),
    ("target:careers", "https://corporate.target.com/careers", "discovery_index"),
    ("walmart:careers", "https://careers.walmart.com", "discovery_index"),
    ("uberindia:careers", "https://www.uber.com/in/en/careers/", "discovery_index"),
    # ── 2. TOP INDIAN TECH UNICORNS & HIGH-GROWTH STARTUPS ───────────────────
    ("razorpay:ashby", "https://jobs.ashbyhq.com/razorpay", "official_ats"),
    ("swiggy:ashby", "https://jobs.ashbyhq.com/swiggy", "official_ats"),
    ("zomato:ashby", "https://jobs.ashbyhq.com/zomato", "official_ats"),
    ("flipkart:ashby", "https://jobs.ashbyhq.com/flipkart", "official_ats"),
    ("meesho:ashby", "https://jobs.ashbyhq.com/meesho", "official_ats"),
    ("urbancompany:ashby", "https://jobs.ashbyhq.com/urbancompany", "official_ats"),
    ("freshworks:ashby", "https://jobs.ashbyhq.com/freshworks", "official_ats"),
    ("chargebee:ashby", "https://jobs.ashbyhq.com/chargebee", "official_ats"),
    ("browserstack:ashby", "https://jobs.ashbyhq.com/browserstack", "official_ats"),
    ("delhivery:ashby", "https://jobs.ashbyhq.com/delhivery", "official_ats"),
    ("mindtickle:ashby", "https://jobs.ashbyhq.com/mindtickle", "official_ats"),
    ("ola:ashby", "https://jobs.ashbyhq.com/ola", "official_ats"),
    ("paytm:ashby", "https://jobs.ashbyhq.com/paytm", "official_ats"),
    ("nykaa:ashby", "https://jobs.ashbyhq.com/nykaa", "official_ats"),
    ("sarvam:ashby", "https://jobs.ashbyhq.com/sarvam", "official_ats"),
    ("krutrim:ashby", "https://jobs.ashbyhq.com/krutrim", "official_ats"),
    ("subspace:ashby", "https://jobs.ashbyhq.com/subspace", "official_ats"),
    ("one2n:ashby", "https://jobs.ashbyhq.com/one2n", "official_ats"),
    ("phonepe:greenhouse", "https://boards.greenhouse.io/phonepe", "official_ats"),
    ("cred:ashby", "https://jobs.ashbyhq.com/cred", "official_ats"),
    ("zepto:ashby", "https://jobs.ashbyhq.com/zepto", "official_ats"),
    ("groww:greenhouse", "https://boards.greenhouse.io/groww", "official_ats"),
    ("postman:greenhouse", "https://boards.greenhouse.io/postman", "official_ats"),
    ("atlan:ashby", "https://jobs.ashbyhq.com/atlan", "official_ats"),
    ("hasura:ashby", "https://jobs.ashbyhq.com/hasura", "official_ats"),
    ("slice:greenhouse", "https://boards.greenhouse.io/slice", "official_ats"),
    ("inmobi:greenhouse", "https://boards.greenhouse.io/inmobi", "official_ats"),
    ("pocketfm:ashby", "https://jobs.ashbyhq.com/pocketfm", "official_ats"),
    ("kukufm:ashby", "https://jobs.ashbyhq.com/kukufm", "official_ats"),
    ("razorpay:workable", "https://apply.workable.com/razorpay", "official_ats"),
    ("swiggy:workable", "https://apply.workable.com/swiggy", "official_ats"),
    ("zoho:careers", "https://careers.zoho.com", "discovery_index"),
    ("darwinbox:careers", "https://darwinbox.com/careers", "discovery_index"),
    ("whatfix:ashby", "https://jobs.ashbyhq.com/whatfix", "official_ats"),
    ("innovaccer:greenhouse", "https://boards.greenhouse.io/innovaccer", "official_ats"),
    ("highradius:careers", "https://www.highradius.com/careers/", "discovery_index"),
    ("uniphore:careers", "https://uniphore.com/careers/", "discovery_index"),
    ("yellowai:careers", "https://yellow.ai/careers/", "discovery_index"),
    ("haptik:careers", "https://haptik.ai/careers", "discovery_index"),
    ("observeai:careers", "https://www.observe.ai/careers", "discovery_index"),
    ("rocketlane:ashby", "https://jobs.ashbyhq.com/rocketlane", "official_ats"),
    ("zluri:careers", "https://www.zluri.com/careers", "discovery_index"),
    ("druva:greenhouse", "https://boards.greenhouse.io/druva", "official_ats"),
    ("icertis:careers", "https://www.icertis.com/company/careers/", "discovery_index"),
    ("sprinklr:greenhouse", "https://boards.greenhouse.io/sprinklr", "official_ats"),
    ("shiprocket:careers", "https://www.shiprocket.in/careers/", "discovery_index"),
    ("udaan:careers", "https://udaan.com/careers", "discovery_index"),
    ("bigbasket:careers", "https://www.bigbasket.com/careers/", "discovery_index"),
    ("blinkit:careers", "https://blinkit.com/careers", "discovery_index"),
    ("rapido:careers", "https://rapido.bike/careers", "discovery_index"),
    ("porter:careers", "https://porter.in/careers", "discovery_index"),
    ("blackbuck:careers", "https://www.blackbuck.com/careers", "discovery_index"),
    ("shadowfax:careers", "https://www.shadowfax.in/careers", "discovery_index"),
    ("xpressbees:careers", "https://www.xpressbees.com/careers", "discovery_index"),
    ("lenskart:careers", "https://www.lenskart.com/careers.html", "discovery_index"),
    ("purplle:careers", "https://www.purplle.com/careers", "discovery_index"),
    ("honasa:careers", "https://www.mamaearth.in/careers", "discovery_index"),
    ("boat:careers", "https://www.boat-lifestyle.com/pages/careers", "discovery_index"),
    ("noise:careers", "https://gonoise.com/pages/careers", "discovery_index"),
    ("licious:careers", "https://www.licious.in/careers", "discovery_index"),
    ("countrydelight:careers", "https://www.countrydelight.in/careers", "discovery_index"),
    ("curefit:careers", "https://www.cult.fit/careers", "discovery_index"),
    ("healthifyme:careers", "https://www.healthifyme.com/careers", "discovery_index"),
    ("pharmeasy:careers", "https://pharmeasy.in/careers/", "discovery_index"),
    ("tata1mg:careers", "https://www.1mg.com/careers", "discovery_index"),
    ("practo:careers", "https://www.practo.com/company/careers", "discovery_index"),
    ("netmeds:careers", "https://www.netmeds.com/careers", "discovery_index"),
    ("apollo247:careers", "https://www.apollo247.com/careers", "discovery_index"),
    ("unacademy:greenhouse", "https://boards.greenhouse.io/unacademy", "official_ats"),
    ("byjus:careers", "https://byjus.com/careers/", "discovery_index"),
    ("vedantu:careers", "https://www.vedantu.com/careers", "discovery_index"),
    ("physicswallah:careers", "https://www.pw.live/careers", "discovery_index"),
    ("simplilearn:careers", "https://www.simplilearn.com/careers", "discovery_index"),
    ("upgrad:careers", "https://www.upgrad.com/careers/", "discovery_index"),
    ("testbook:careers", "https://testbook.com/careers", "discovery_index"),
    ("leadsquared:ashby", "https://jobs.ashbyhq.com/leadsquared", "official_ats"),
    ("kissflow:careers", "https://kissflow.com/careers/", "discovery_index"),
    ("vwo:careers", "https://vwo.com/careers/", "discovery_index"),
    ("cashfree:greenhouse", "https://boards.greenhouse.io/cashfreepayments", "official_ats"),
    ("instamojo:careers", "https://www.instamojo.com/careers/", "discovery_index"),
    ("payu:careers", "https://corporate.payu.in/careers/", "discovery_index"),
    ("bharatpe:careers", "https://bharatpe.com/careers", "discovery_index"),
    ("pinelabs:careers", "https://www.pinelabs.com/careers", "discovery_index"),
    ("simpl:careers", "https://www.getsimpl.com/careers", "discovery_index"),
    ("lazypay:careers", "https://www.lazypay.in/careers", "discovery_index"),
    ("kreditbee:careers", "https://www.kreditbee.in/careers", "discovery_index"),
    ("jupiter:ashby", "https://jobs.ashbyhq.com/jupiter", "official_ats"),
    ("fimoney:careers", "https://fi.money/careers", "discovery_index"),
    ("niyo:careers", "https://goniyo.com/careers/", "discovery_index"),
    ("setu:careers", "https://setu.co/careers", "discovery_index"),
    ("signzy:careers", "https://signzy.com/careers/", "discovery_index"),
    ("hyperverge:careers", "https://hyperverge.co/careers/", "discovery_index"),
    ("perfios:careers", "https://perfios.com/careers/", "discovery_index"),
    ("upstox:careers", "https://upstox.com/careers/", "discovery_index"),
    ("zerodha:careers", "https://zerodha.com/careers/", "discovery_index"),
    ("angelone:careers", "https://www.angelone.in/careers", "discovery_index"),
    ("smallcase:ashby", "https://jobs.ashbyhq.com/smallcase", "official_ats"),
    ("indmoney:careers", "https://indmoney.com/careers", "discovery_index"),
    ("dhan:careers", "https://dhan.co/careers/", "discovery_index"),
    # ── 3. HIGH-PAYING HFTs & QUANT FINANCE IN INDIA ──────────────────────────
    (
        "tower-research:greenhouse",
        "https://boards.greenhouse.io/towerresearchcapital",
        "official_ats",
    ),
    ("deshaw:careers", "https://www.deshawindia.com/careers", "discovery_index"),
    ("graviton:ashby", "https://jobs.ashbyhq.com/graviton", "official_ats"),
    ("squarepoint:greenhouse", "https://boards.greenhouse.io/squarepointcapital", "official_ats"),
    ("quantbox:ashby", "https://jobs.ashbyhq.com/quantbox", "official_ats"),
    (
        "optiver:careers",
        "https://optiver.com/working-at-optiver/career-opportunities/",
        "discovery_index",
    ),
    ("imc:careers", "https://careers.imc.com", "discovery_index"),
    ("jumptrading:careers", "https://www.jumptrading.com/careers/", "discovery_index"),
    (
        "janestreet:careers",
        "https://www.janestreet.com/join-jane-street/open-roles/",
        "discovery_index",
    ),
    ("citadelsecurities:careers", "https://www.citadelsecurities.com/careers/", "discovery_index"),
    ("twosigma:careers", "https://www.twosigma.com/careers/", "discovery_index"),
    (
        "hudsonrivertrading:careers",
        "https://www.hudsonrivertrading.com/careers/",
        "discovery_index",
    ),
    ("drw:careers", "https://drw.com/careers", "discovery_index"),
    ("sig:careers", "https://careers.sig.com", "discovery_index"),
    ("akunacapital:careers", "https://akunacapital.com/careers", "discovery_index"),
    ("flowtraders:careers", "https://flowtraders.com/careers", "discovery_index"),
    ("xtxmarkets:careers", "https://www.xtxmarkets.com/careers/", "discovery_index"),
    ("gsacapital:careers", "https://www.gsacapital.com/careers", "discovery_index"),
    ("millennium:careers", "https://www.mlp.com/careers/", "discovery_index"),
    ("pointsetentytwo:careers", "https://www.point72.com/careers/", "discovery_index"),
    ("balyasny:careers", "https://www.bamfunds.com/careers/", "discovery_index"),
    ("mangroup:careers", "https://www.man.com/careers", "discovery_index"),
    ("worldquant:careers", "https://www.worldquant.com/careers/", "discovery_index"),
    ("aqr:careers", "https://www.aqr.com/About-Us/Careers", "discovery_index"),
    # ── 4. FRONTIER AI LABS & MODERN AI STARTUPS ──────────────────────────────
    ("openai:ashby", "https://jobs.ashbyhq.com/openai", "official_ats"),
    ("anthropic:ashby", "https://jobs.ashbyhq.com/anthropic", "official_ats"),
    ("huggingface:ashby", "https://jobs.ashbyhq.com/huggingface", "official_ats"),
    ("groq:ashby", "https://jobs.ashbyhq.com/groq", "official_ats"),
    ("cohere:ashby", "https://jobs.ashbyhq.com/cohere", "official_ats"),
    ("characterai:ashby", "https://jobs.ashbyhq.com/characterai", "official_ats"),
    ("cognition:ashby", "https://jobs.ashbyhq.com/cognition", "official_ats"),
    ("runway:ashby", "https://jobs.ashbyhq.com/runway", "official_ats"),
    ("mistral:ashby", "https://jobs.ashbyhq.com/mistral", "official_ats"),
    ("anysphere:ashby", "https://jobs.ashbyhq.com/anysphere", "official_ats"),
    ("elevenlabs:ashby", "https://jobs.ashbyhq.com/elevenlabs", "official_ats"),
    ("perplexity:ashby", "https://jobs.ashbyhq.com/perplexity", "official_ats"),
    ("together:ashby", "https://jobs.ashbyhq.com/together", "official_ats"),
    ("harvey:ashby", "https://jobs.ashbyhq.com/harvey", "official_ats"),
    ("xai:careers", "https://x.ai/careers", "discovery_index"),
    ("inflection:careers", "https://inflection.ai/careers", "discovery_index"),
    ("adept:careers", "https://www.adept.ai/careers", "discovery_index"),
    ("stabilityai:careers", "https://stability.ai/careers", "discovery_index"),
    ("suno:ashby", "https://jobs.ashbyhq.com/suno", "official_ats"),
    ("lumaai:ashby", "https://jobs.ashbyhq.com/lumalabs", "official_ats"),
    ("pika:careers", "https://pika.art/careers", "discovery_index"),
    ("synthesia:ashby", "https://jobs.ashbyhq.com/synthesia", "official_ats"),
    ("sierra:ashby", "https://jobs.ashbyhq.com/sierra", "official_ats"),
    ("glean:greenhouse", "https://boards.greenhouse.io/gleanwork", "official_ats"),
    ("writer:greenhouse", "https://boards.greenhouse.io/getwriter", "official_ats"),
    ("jasper:greenhouse", "https://boards.greenhouse.io/jasperai", "official_ats"),
    ("fireworksai:ashby", "https://jobs.ashbyhq.com/fireworksai", "official_ats"),
    ("baseten:ashby", "https://jobs.ashbyhq.com/baseten", "official_ats"),
    ("replicate:ashby", "https://jobs.ashbyhq.com/replicate", "official_ats"),
    ("anyscale:greenhouse", "https://boards.greenhouse.io/anyscale", "official_ats"),
    ("contextualai:ashby", "https://jobs.ashbyhq.com/contextualai", "official_ats"),
    ("rekaai:careers", "https://www.reka.ai/careers", "discovery_index"),
    ("imbue:ashby", "https://jobs.ashbyhq.com/imbue", "official_ats"),
    ("worldlabs:careers", "https://www.worldlabs.ai/careers", "discovery_index"),
    (
        "physicalintelligence:careers",
        "https://www.physicalintelligence.company/careers",
        "discovery_index",
    ),
    ("skildai:careers", "https://www.skild.ai/careers", "discovery_index"),
    ("figure:greenhouse", "https://boards.greenhouse.io/figureai", "official_ats"),
    ("1x:careers", "https://www.1x.tech/careers", "discovery_index"),
    ("covariant:greenhouse", "https://boards.greenhouse.io/covariant", "official_ats"),
    ("deepgram:ashby", "https://jobs.ashbyhq.com/deepgram", "official_ats"),
    ("assemblyai:ashby", "https://jobs.ashbyhq.com/assemblyai", "official_ats"),
    ("voiceflow:ashby", "https://jobs.ashbyhq.com/voiceflow", "official_ats"),
    ("clay:ashby", "https://jobs.ashbyhq.com/clay", "official_ats"),
    ("apollo-io:ashby", "https://jobs.ashbyhq.com/apollo", "official_ats"),
    # ── 5. DEV TOOLS, CLOUD & AI INFRASTRUCTURE ─────────────────────────────
    ("linear:ashby", "https://jobs.ashbyhq.com/linear", "official_ats"),
    ("vercel:ashby", "https://jobs.ashbyhq.com/vercel", "official_ats"),
    ("retool:ashby", "https://jobs.ashbyhq.com/retool", "official_ats"),
    ("ramp:ashby", "https://jobs.ashbyhq.com/ramp", "official_ats"),
    ("posthog:ashby", "https://jobs.ashbyhq.com/posthog", "official_ats"),
    ("modal:ashby", "https://jobs.ashbyhq.com/modal", "official_ats"),
    ("replit:ashby", "https://jobs.ashbyhq.com/replit", "official_ats"),
    ("supabase:ashby", "https://jobs.ashbyhq.com/supabase", "official_ats"),
    ("railway:ashby", "https://jobs.ashbyhq.com/railway", "official_ats"),
    ("neon:ashby", "https://jobs.ashbyhq.com/neon", "official_ats"),
    ("resend:ashby", "https://jobs.ashbyhq.com/resend", "official_ats"),
    ("langchain:ashby", "https://jobs.ashbyhq.com/langchain", "official_ats"),
    ("llamaindex:ashby", "https://jobs.ashbyhq.com/llamaindex", "official_ats"),
    ("pinecone:ashby", "https://jobs.ashbyhq.com/pinecone", "official_ats"),
    ("weaviate:ashby", "https://jobs.ashbyhq.com/weaviate", "official_ats"),
    ("qdrant:ashby", "https://jobs.ashbyhq.com/qdrant", "official_ats"),
    ("flyio:ashby", "https://jobs.ashbyhq.com/flyio", "official_ats"),
    ("render:ashby", "https://jobs.ashbyhq.com/render", "official_ats"),
    ("framer:ashby", "https://jobs.ashbyhq.com/framer", "official_ats"),
    ("notion:ashby", "https://jobs.ashbyhq.com/notion", "official_ats"),
    ("scaleai:ashby", "https://jobs.ashbyhq.com/scaleai", "official_ats"),
    ("snowflake:ashby", "https://jobs.ashbyhq.com/snowflake", "official_ats"),
    ("temporal:ashby", "https://jobs.ashbyhq.com/temporal", "official_ats"),
    ("airbyte:ashby", "https://jobs.ashbyhq.com/airbyte", "official_ats"),
    ("dbtlabs:greenhouse", "https://boards.greenhouse.io/dbtlabs", "official_ats"),
    ("fivetran:greenhouse", "https://boards.greenhouse.io/fivetran", "official_ats"),
    ("census:ashby", "https://jobs.ashbyhq.com/getcensus", "official_ats"),
    ("hightouch:ashby", "https://jobs.ashbyhq.com/hightouch", "official_ats"),
    ("montecarlodata:greenhouse", "https://boards.greenhouse.io/montecarlodata", "official_ats"),
    ("sigmacomputing:greenhouse", "https://boards.greenhouse.io/sigmacomputing", "official_ats"),
    ("hex:ashby", "https://jobs.ashbyhq.com/hex", "official_ats"),
    ("deepnote:ashby", "https://jobs.ashbyhq.com/deepnote", "official_ats"),
    ("grafanalabs:greenhouse", "https://boards.greenhouse.io/grafanalabs", "official_ats"),
    ("honeycomb:greenhouse", "https://boards.greenhouse.io/honeycombio", "official_ats"),
    ("chronosphere:greenhouse", "https://boards.greenhouse.io/chronosphere", "official_ats"),
    ("axiom:ashby", "https://jobs.ashbyhq.com/axiom", "official_ats"),
    ("highlight:ashby", "https://jobs.ashbyhq.com/highlight", "official_ats"),
    ("sentry:greenhouse", "https://boards.greenhouse.io/sentry", "official_ats"),
    ("logrocket:greenhouse", "https://boards.greenhouse.io/logrocket", "official_ats"),
    ("fullstory:greenhouse", "https://boards.greenhouse.io/fullstory", "official_ats"),
    ("statsig:ashby", "https://jobs.ashbyhq.com/statsig", "official_ats"),
    ("launchdarkly:greenhouse", "https://boards.greenhouse.io/launchdarkly", "official_ats"),
    ("optimizely:greenhouse", "https://boards.greenhouse.io/optimizely", "official_ats"),
    ("segment:greenhouse", "https://boards.greenhouse.io/segment", "official_ats"),
    ("mparticle:greenhouse", "https://boards.greenhouse.io/mparticle", "official_ats"),
    ("contentful:greenhouse", "https://boards.greenhouse.io/contentful", "official_ats"),
    ("sanity:ashby", "https://jobs.ashbyhq.com/sanity", "official_ats"),
    ("strapi:ashby", "https://jobs.ashbyhq.com/strapi", "official_ats"),
    ("clickhouse:ashby", "https://jobs.ashbyhq.com/clickhouse", "official_ats"),
    ("cockroachlabs:greenhouse", "https://boards.greenhouse.io/cockroachlabs", "official_ats"),
    ("redis:greenhouse", "https://boards.greenhouse.io/redislabs", "official_ats"),
    ("couchbase:greenhouse", "https://boards.greenhouse.io/couchbase", "official_ats"),
    ("neo4j:greenhouse", "https://boards.greenhouse.io/neo4j", "official_ats"),
    ("timescale:ashby", "https://jobs.ashbyhq.com/timescale", "official_ats"),
    ("planetscale:ashby", "https://jobs.ashbyhq.com/planetscale", "official_ats"),
    ("fauna:greenhouse", "https://boards.greenhouse.io/fauna", "official_ats"),
    ("digitalocean:greenhouse", "https://boards.greenhouse.io/digitalocean", "official_ats"),
    ("linode:greenhouse", "https://boards.greenhouse.io/linode", "official_ats"),
    ("backblaze:greenhouse", "https://boards.greenhouse.io/backblaze", "official_ats"),
    ("box:greenhouse", "https://boards.greenhouse.io/box", "official_ats"),
    ("dropbox:greenhouse", "https://boards.greenhouse.io/dropbox", "official_ats"),
    ("smartsheet:greenhouse", "https://boards.greenhouse.io/smartsheet", "official_ats"),
    ("monday:careers", "https://monday.com/careers", "discovery_index"),
    ("airtable:greenhouse", "https://boards.greenhouse.io/airtable", "official_ats"),
    ("clickup:greenhouse", "https://boards.greenhouse.io/clickup", "official_ats"),
    ("miro:greenhouse", "https://boards.greenhouse.io/miro", "official_ats"),
    ("canva:careers", "https://www.lifeatcanva.com/en/jobs/", "discovery_index"),
    ("coda:greenhouse", "https://boards.greenhouse.io/coda", "official_ats"),
    ("height:ashby", "https://jobs.ashbyhq.com/height", "official_ats"),
    ("wix:careers", "https://www.wix.com/jobs/careers", "discovery_index"),
    ("bubble:ashby", "https://jobs.ashbyhq.com/bubble", "official_ats"),
    ("zapier:ashby", "https://jobs.ashbyhq.com/zapier", "official_ats"),
    ("make:careers", "https://www.make.com/en/careers", "discovery_index"),
    ("n8n:ashby", "https://jobs.ashbyhq.com/n8n", "official_ats"),
    ("uipath:greenhouse", "https://boards.greenhouse.io/uipath", "official_ats"),
    ("workato:greenhouse", "https://boards.greenhouse.io/workato", "official_ats"),
    ("boomi:careers", "https://boomi.com/careers/", "discovery_index"),
    ("sendgrid:careers", "https://sendgrid.com/en-us/careers", "discovery_index"),
    ("postmark:careers", "https://postmarkapp.com/careers", "discovery_index"),
    ("mailgun:careers", "https://www.mailgun.com/careers/", "discovery_index"),
    ("customerio:ashby", "https://jobs.ashbyhq.com/customerio", "official_ats"),
    ("intercom:greenhouse", "https://boards.greenhouse.io/intercom", "official_ats"),
    ("front:greenhouse", "https://boards.greenhouse.io/frontapp", "official_ats"),
    ("gong:greenhouse", "https://boards.greenhouse.io/gong", "official_ats"),
    ("outreach:greenhouse", "https://boards.greenhouse.io/outreach", "official_ats"),
    ("clari:greenhouse", "https://boards.greenhouse.io/clari", "official_ats"),
    ("zoominfo:greenhouse", "https://boards.greenhouse.io/zoominfo", "official_ats"),
    ("sixsense:greenhouse", "https://boards.greenhouse.io/6sense", "official_ats"),
    ("drift:greenhouse", "https://boards.greenhouse.io/drift", "official_ats"),
    ("braze:greenhouse", "https://boards.greenhouse.io/braze", "official_ats"),
    ("klaviyo:greenhouse", "https://boards.greenhouse.io/klaviyo", "official_ats"),
    ("iterable:greenhouse", "https://boards.greenhouse.io/iterable", "official_ats"),
    ("amplitude:greenhouse", "https://boards.greenhouse.io/amplitude", "official_ats"),
    ("mixpanel:greenhouse", "https://boards.greenhouse.io/mixpanel", "official_ats"),
    ("heap:greenhouse", "https://boards.greenhouse.io/heapinc", "official_ats"),
    ("convertkit:ashby", "https://jobs.ashbyhq.com/convertkit", "official_ats"),
    ("beehiiv:ashby", "https://jobs.ashbyhq.com/beehiiv", "official_ats"),
    ("substack:ashby", "https://jobs.ashbyhq.com/substack", "official_ats"),
    ("ghost:careers", "https://ghost.org/about/#jobs", "discovery_index"),
    # ── 6. TOP UNICORNS & TECH OPERATIONS (Ashby & Greenhouse) ─────────────
    ("rippling:ashby", "https://jobs.ashbyhq.com/rippling", "official_ats"),
    ("deel:ashby", "https://jobs.ashbyhq.com/deel", "official_ats"),
    ("doordash:ashby", "https://jobs.ashbyhq.com/doordash", "official_ats"),
    ("chime:ashby", "https://jobs.ashbyhq.com/chime", "official_ats"),
    ("plaid:ashby", "https://jobs.ashbyhq.com/plaid", "official_ats"),
    ("coinbase:ashby", "https://jobs.ashbyhq.com/coinbase", "official_ats"),
    ("robinhood:ashby", "https://jobs.ashbyhq.com/robinhood", "official_ats"),
    ("uber:ashby", "https://jobs.ashbyhq.com/uber", "official_ats"),
    ("lyft:ashby", "https://jobs.ashbyhq.com/lyft", "official_ats"),
    ("pinterest:ashby", "https://jobs.ashbyhq.com/pinterest", "official_ats"),
    ("asana:ashby", "https://jobs.ashbyhq.com/asana", "official_ats"),
    ("webflow:ashby", "https://jobs.ashbyhq.com/webflow", "official_ats"),
    ("shopify:ashby", "https://jobs.ashbyhq.com/shopify", "official_ats"),
    ("stripe:greenhouse", "https://boards.greenhouse.io/stripe", "official_ats"),
    ("airbnb:greenhouse", "https://boards.greenhouse.io/airbnb", "official_ats"),
    ("figma:greenhouse", "https://boards.greenhouse.io/figma", "official_ats"),
    ("databricks:greenhouse", "https://boards.greenhouse.io/databricks", "official_ats"),
    ("scaleai:greenhouse", "https://boards.greenhouse.io/scaleai", "official_ats"),
    ("robinhood:greenhouse", "https://boards.greenhouse.io/robinhood", "official_ats"),
    ("lyft:greenhouse", "https://boards.greenhouse.io/lyft", "official_ats"),
    ("reddit:greenhouse", "https://boards.greenhouse.io/reddit", "official_ats"),
    ("brex:greenhouse", "https://boards.greenhouse.io/brex", "official_ats"),
    ("gusto:greenhouse", "https://boards.greenhouse.io/gusto", "official_ats"),
    ("cloudflare:greenhouse", "https://boards.greenhouse.io/cloudflare", "official_ats"),
    ("datadog:greenhouse", "https://boards.greenhouse.io/datadog", "official_ats"),
    ("mongodb:greenhouse", "https://boards.greenhouse.io/mongodb", "official_ats"),
    ("elastic:greenhouse", "https://boards.greenhouse.io/elastic", "official_ats"),
    ("twilio:greenhouse", "https://boards.greenhouse.io/twilio", "official_ats"),
    ("duolingo:greenhouse", "https://boards.greenhouse.io/duolingo", "official_ats"),
    ("affirm:greenhouse", "https://boards.greenhouse.io/affirm", "official_ats"),
    ("discord:greenhouse", "https://boards.greenhouse.io/discord", "official_ats"),
    ("instacart:greenhouse", "https://boards.greenhouse.io/instacart", "official_ats"),
    ("gitlab:greenhouse", "https://boards.greenhouse.io/gitlab", "official_ats"),
    ("hubspot:greenhouse", "https://boards.greenhouse.io/hubspot", "official_ats"),
    ("block:greenhouse", "https://boards.greenhouse.io/block", "official_ats"),
    ("okta:greenhouse", "https://boards.greenhouse.io/okta", "official_ats"),
    ("fastly:greenhouse", "https://boards.greenhouse.io/fastly", "official_ats"),
    ("zscaler:greenhouse", "https://boards.greenhouse.io/zscaler", "official_ats"),
    ("palantir:lever", "https://jobs.lever.co/palantir", "official_ats"),
    ("spotify:lever", "https://jobs.lever.co/spotify", "official_ats"),
    ("ycombinator:jobs", "https://www.ycombinator.com/jobs", "discovery_index"),
    # ── 7. FINTECH & CRYPTO (GLOBAL) ─────────────────────────────────────────
    ("kraken:greenhouse", "https://boards.greenhouse.io/kraken", "official_ats"),
    ("gemini:greenhouse", "https://boards.greenhouse.io/gemini", "official_ats"),
    ("circle:greenhouse", "https://boards.greenhouse.io/circle", "official_ats"),
    ("chainalysis:greenhouse", "https://boards.greenhouse.io/chainalysis", "official_ats"),
    ("anchorage:greenhouse", "https://boards.greenhouse.io/anchoragedigital", "official_ats"),
    ("consensys:greenhouse", "https://boards.greenhouse.io/consensys", "official_ats"),
    ("uniswaplabs:ashby", "https://jobs.ashbyhq.com/uniswaplabs", "official_ats"),
    ("opensea:ashby", "https://jobs.ashbyhq.com/opensea", "official_ats"),
    ("alchemy:ashby", "https://jobs.ashbyhq.com/alchemy", "official_ats"),
    ("fireblocks:greenhouse", "https://boards.greenhouse.io/fireblocks", "official_ats"),
    ("bitgo:greenhouse", "https://boards.greenhouse.io/bitgo", "official_ats"),
    ("betterment:greenhouse", "https://boards.greenhouse.io/betterment", "official_ats"),
    ("wealthfront:greenhouse", "https://boards.greenhouse.io/wealthfront", "official_ats"),
    ("addepar:greenhouse", "https://boards.greenhouse.io/addepar", "official_ats"),
    ("carta:greenhouse", "https://boards.greenhouse.io/carta", "official_ats"),
    ("opendoor:greenhouse", "https://boards.greenhouse.io/opendoor", "official_ats"),
    ("compass:greenhouse", "https://boards.greenhouse.io/compass", "official_ats"),
    ("better:greenhouse", "https://boards.greenhouse.io/better", "official_ats"),
    ("sofi:greenhouse", "https://boards.greenhouse.io/sofi", "official_ats"),
    ("creditkarma:greenhouse", "https://boards.greenhouse.io/creditkarma", "official_ats"),
    ("mercury:ashby", "https://jobs.ashbyhq.com/mercury", "official_ats"),
    ("brex:ashby", "https://jobs.ashbyhq.com/brex", "official_ats"),
    ("wise:greenhouse", "https://boards.greenhouse.io/transferwise", "official_ats"),
    ("revolut:careers", "https://www.revolut.com/careers/", "discovery_index"),
    ("n26:careers", "https://n26.com/en-eu/careers", "discovery_index"),
    ("monzo:careers", "https://monzo.com/careers/", "discovery_index"),
    ("klarna:careers", "https://www.klarna.com/careers/", "discovery_index"),
    ("adyen:careers", "https://careers.adyen.com", "discovery_index"),
    ("checkout:greenhouse", "https://boards.greenhouse.io/checkoutcom", "official_ats"),
    ("marqeta:greenhouse", "https://boards.greenhouse.io/marqeta", "official_ats"),
    ("bill:greenhouse", "https://boards.greenhouse.io/billcom", "official_ats"),
    ("toast:greenhouse", "https://boards.greenhouse.io/toasttab", "official_ats"),
    ("squareup:greenhouse", "https://boards.greenhouse.io/squareup", "official_ats"),
    # ── 8. GAMING & ENTERTAINMENT ────────────────────────────────────────────
    ("epicgames:careers", "https://www.epicgames.com/site/en-US/careers", "discovery_index"),
    ("riotgames:careers", "https://www.riotgames.com/en/work-with-us", "discovery_index"),
    ("unity:greenhouse", "https://boards.greenhouse.io/unity3d", "official_ats"),
    ("roblox:greenhouse", "https://boards.greenhouse.io/roblox", "official_ats"),
    ("valve:careers", "https://www.valvesoftware.com/en/jobs", "discovery_index"),
    ("ea:careers", "https://www.ea.com/careers", "discovery_index"),
    ("ubisoft:careers", "https://www.ubisoft.com/en-us/company/careers", "discovery_index"),
    ("activisionblizzard:careers", "https://careers.activisionblizzard.com", "discovery_index"),
    ("supercell:careers", "https://supercell.com/en/careers/", "discovery_index"),
    ("king:careers", "https://careers.king.com", "discovery_index"),
    ("nianticlabs:greenhouse", "https://boards.greenhouse.io/nianticlabs", "official_ats"),
    ("discordgames:careers", "https://discord.com/careers", "discovery_index"),
    ("netflix:careers", "https://jobs.netflix.com", "discovery_index"),
    ("disney:careers", "https://jobs.disneycareers.com", "discovery_index"),
    ("warnerbros:careers", "https://careers.wbd.com", "discovery_index"),
    # ── 9. HEALTHTECH & BIOTECH ──────────────────────────────────────────────
    ("oscarhealth:greenhouse", "https://boards.greenhouse.io/oscarhealth", "official_ats"),
    ("devotedhealth:greenhouse", "https://boards.greenhouse.io/devotedhealth", "official_ats"),
    ("carbonhealth:greenhouse", "https://boards.greenhouse.io/carbonhealth", "official_ats"),
    ("cerebral:greenhouse", "https://boards.greenhouse.io/cerebral", "official_ats"),
    ("headspace:greenhouse", "https://boards.greenhouse.io/headspace", "official_ats"),
    ("calm:greenhouse", "https://boards.greenhouse.io/calm", "official_ats"),
    ("tempus:greenhouse", "https://boards.greenhouse.io/tempus", "official_ats"),
    ("flatironhealth:greenhouse", "https://boards.greenhouse.io/flatironhealth", "official_ats"),
    ("benchling:ashby", "https://jobs.ashbyhq.com/benchling", "official_ats"),
    ("moderna:careers", "https://www.modernatx.com/careers", "discovery_index"),
    ("23andme:greenhouse", "https://boards.greenhouse.io/23andme", "official_ats"),
    (
        "babylonhealth:careers",
        "https://www.babylonhealth.com/en-us/careers",
        "discovery_index",
    ),
    ("teladoc:careers", "https://www.teladochealth.com/careers/", "discovery_index"),
    # ── 10. PROPTECH, MARKETPLACES & LOGISTICS ──────────────────────────────
    ("faire:greenhouse", "https://boards.greenhouse.io/faire", "official_ats"),
    ("convoy:greenhouse", "https://boards.greenhouse.io/convoy", "official_ats"),
    ("flexport:greenhouse", "https://boards.greenhouse.io/flexport", "official_ats"),
    ("samsara:greenhouse", "https://boards.greenhouse.io/samsara", "official_ats"),
    ("thumbtack:greenhouse", "https://boards.greenhouse.io/thumbtack", "official_ats"),
    ("wayfair:careers", "https://www.aboutwayfair.com/careers", "discovery_index"),
    ("zillow:careers", "https://www.zillow.com/careers/", "discovery_index"),
    ("redfin:greenhouse", "https://boards.greenhouse.io/redfin", "official_ats"),
    ("angi:careers", "https://www.angi.com/careers", "discovery_index"),
    ("procore:greenhouse", "https://boards.greenhouse.io/procoretechnologies", "official_ats"),
    # ── 11. HRTECH & RECRUITING TECH ─────────────────────────────────────────
    ("lever:careers", "https://www.lever.co/careers", "discovery_index"),
    ("greenhouse:greenhouse", "https://boards.greenhouse.io/greenhouse", "official_ats"),
    ("ashbyhq:ashby", "https://jobs.ashbyhq.com/ashby", "official_ats"),
    ("gusto:careers", "https://gusto.com/about/careers", "discovery_index"),
    ("bamboohr:careers", "https://www.bamboohr.com/careers/", "discovery_index"),
    ("justworks:greenhouse", "https://boards.greenhouse.io/justworks", "official_ats"),
    ("papayaglobal:ashby", "https://jobs.ashbyhq.com/papayaglobal", "official_ats"),
    ("remote:ashby", "https://jobs.ashbyhq.com/remote", "official_ats"),
    ("oysterhr:ashby", "https://jobs.ashbyhq.com/oysterhr", "official_ats"),
    ("velocityglobal:careers", "https://velocityglobal.com/careers/", "discovery_index"),
    # ── 12. CYBERSECURITY ────────────────────────────────────────────────────
    ("crowdstrike:careers", "https://www.crowdstrike.com/careers/", "discovery_index"),
    ("sentinelone:greenhouse", "https://boards.greenhouse.io/sentinelone", "official_ats"),
    ("netskope:greenhouse", "https://boards.greenhouse.io/netskope", "official_ats"),
    ("lacework:greenhouse", "https://boards.greenhouse.io/lacework", "official_ats"),
    ("snyk:greenhouse", "https://boards.greenhouse.io/snyk", "official_ats"),
    ("jfrog:greenhouse", "https://boards.greenhouse.io/jfrog", "official_ats"),
    ("wiz:greenhouse", "https://boards.greenhouse.io/wizinc", "official_ats"),
    ("1password:ashby", "https://jobs.ashbyhq.com/1password", "official_ats"),
    ("tailscale:ashby", "https://jobs.ashbyhq.com/tailscale", "official_ats"),
    ("cloudflare:ashby", "https://jobs.ashbyhq.com/cloudflare", "official_ats"),
    ("orca-security:greenhouse", "https://boards.greenhouse.io/orcasecurity", "official_ats"),
    (
        "abnormalsecurity:greenhouse",
        "https://boards.greenhouse.io/abnormalsecurity",
        "official_ats",
    ),
    ("huntress:ashby", "https://jobs.ashbyhq.com/huntress", "official_ats"),
    ("semgrep:ashby", "https://jobs.ashbyhq.com/semgrep", "official_ats"),
    ("vanta:ashby", "https://jobs.ashbyhq.com/vanta", "official_ats"),
    ("drata:ashby", "https://jobs.ashbyhq.com/drata", "official_ats"),
    # ── 13. TRAVEL TECH ───────────────────────────────────────────────────────
    ("airbnb:careers", "https://careers.airbnb.com", "discovery_index"),
    ("booking:careers", "https://careers.booking.com", "discovery_index"),
    ("expedia:careers", "https://careers.expediagroup.com", "discovery_index"),
    ("makemytrip:careers", "https://careers.makemytrip.com", "discovery_index"),
    ("goibibo:careers", "https://www.goibibo.com/careers/", "discovery_index"),
    ("oyo:greenhouse", "https://boards.greenhouse.io/oyorooms", "official_ats"),
    ("ixigo:careers", "https://www.ixigo.com/careers", "discovery_index"),
    ("cleartrip:careers", "https://www.cleartrip.com/careers", "discovery_index"),
    ("treebo:careers", "https://www.treebo.com/careers", "discovery_index"),
    # ── 14. MEDIA & STREAMING ────────────────────────────────────────────────
    ("spotify:careers", "https://www.lifeatspotify.com/jobs", "discovery_index"),
    ("soundcloud:greenhouse", "https://boards.greenhouse.io/soundcloud", "official_ats"),
    ("audible:careers", "https://www.audible.com/careers", "discovery_index"),
    ("hotstar:careers", "https://careers.hotstar.com", "discovery_index"),
    ("jiocinema:careers", "https://www.jio.com/careers", "discovery_index"),
    ("sonyliv:careers", "https://www.sonypictures.com/corp/careers", "discovery_index"),
    ("zee5:careers", "https://www.zee.com/careers/", "discovery_index"),
    # ── 15. REMOTE-FIRST / GLOBAL DISTRIBUTED COMPANIES ─────────────────────
    ("gitlab:remote", "https://about.gitlab.com/jobs/", "discovery_index"),
    ("automattic:careers", "https://automattic.com/work-with-us/", "discovery_index"),
    ("zapier:remote", "https://zapier.com/jobs", "discovery_index"),
    ("doist:careers", "https://doist.com/careers", "discovery_index"),
    ("basecamp:careers", "https://basecamp.com/about/jobs", "discovery_index"),
    ("buffer:careers", "https://buffer.com/journey", "discovery_index"),
    ("toggl:careers", "https://toggl.com/jobs/", "discovery_index"),
    ("invisiontech:greenhouse", "https://boards.greenhouse.io/invisionapp", "official_ats"),
    ("close:ashby", "https://jobs.ashbyhq.com/close", "official_ats"),
    ("gitpod:ashby", "https://jobs.ashbyhq.com/gitpod", "official_ats"),
    ("hashicorp:greenhouse", "https://boards.greenhouse.io/hashicorp", "official_ats"),
    ("elastic:careers", "https://www.elastic.co/careers", "discovery_index"),
    ("canonical:careers", "https://canonical.com/careers", "discovery_index"),
    ("mozilla:careers", "https://www.mozilla.org/en-US/careers/listings/", "discovery_index"),
    ("wordpress:careers", "https://jobs.automattic.com", "discovery_index"),
    # ── 16. INDIAN IT SERVICES & GCC / GLOBAL CAPABILITY CENTRES ────────────
    ("ltimindtree:careers", "https://www.ltimindtree.com/careers/", "discovery_index"),
    ("mphasis:careers", "https://careers.mphasis.com", "discovery_index"),
    ("persistent:careers", "https://www.persistent.com/careers/", "discovery_index"),
    ("mindtree:careers", "https://www.mindtree.com/careers", "discovery_index"),
    ("hexaware:careers", "https://hexaware.com/careers/", "discovery_index"),
    ("coforge:careers", "https://www.coforge.com/careers", "discovery_index"),
    ("birlasoft:careers", "https://www.birlasoft.com/careers", "discovery_index"),
    ("zensar:careers", "https://www.zensar.com/careers", "discovery_index"),
    ("sonata-software:careers", "https://www.sonata-software.com/careers", "discovery_index"),
    ("cyient:careers", "https://www.cyient.com/careers", "discovery_index"),
    ("gspann:careers", "https://www.gspann.com/careers/", "discovery_index"),
    ("thoughtworks:careers", "https://www.thoughtworks.com/careers", "discovery_index"),
    ("epam:careers", "https://www.epam.com/careers", "discovery_index"),
    ("globallogic:careers", "https://www.globallogic.com/careers/", "discovery_index"),
    ("publicissapient:careers", "https://www.publicissapient.com/careers", "discovery_index"),
    ("virtusa:careers", "https://www.virtusa.com/careers", "discovery_index"),
    ("mastech-digital:careers", "https://www.mastechdigital.com/careers/", "discovery_index"),
    # ── 17. SEMICONDUCTOR & HARDWARE (EXTENDED) ──────────────────────────────
    ("marvell:careers", "https://careers.marvell.com", "discovery_index"),
    ("mediatek:careers", "https://careers.mediatek.com", "discovery_index"),
    ("skyworks:careers", "https://www.skyworksinc.com/en/Careers", "discovery_index"),
    (
        "analogdevices:careers",
        "https://www.analog.com/en/about-adi/careers.html",
        "discovery_index",
    ),
    ("onsemi:careers", "https://www.onsemi.com/careers", "discovery_index"),
    (
        "cadence:careers",
        "https://www.cadence.com/en_US/home/company/careers.html",
        "discovery_index",
    ),
    ("synopsys:careers", "https://www.synopsys.com/careers.html", "discovery_index"),
    ("cirrus-logic:careers", "https://www.cirrus.com/careers/", "discovery_index"),
    ("renesas:careers", "https://www.renesas.com/us/en/about/careers", "discovery_index"),
    (
        "stmicroelectronics:careers",
        "https://www.st.com/content/st_com/en/about/st_careers.html",
        "discovery_index",
    ),
    # ── 18. GLOBAL BANKS & FINANCIAL SERVICES (EXTENDED) ─────────────────────
    ("citigroup:careers", "https://jobs.citi.com", "discovery_index"),
    ("bankofamerica:careers", "https://careers.bankofamerica.com", "discovery_index"),
    ("wellsfargo:careers", "https://www.wellsfargojobs.com", "discovery_index"),
    ("ubs:careers", "https://www.ubs.com/global/en/careers.html", "discovery_index"),
    (
        "creditsuisse:careers",
        "https://www.credit-suisse.com/about-us/en/careers.html",
        "discovery_index",
    ),
    ("standardchartered:careers", "https://www.sc.com/en/careers/", "discovery_index"),
    ("axisbank:careers", "https://careers.axisbank.com", "discovery_index"),
    ("hdfcbank:careers", "https://www.hdfcbank.com/careers", "discovery_index"),
    ("icicibank:careers", "https://www.icicicareers.com", "discovery_index"),
    ("kotakbank:careers", "https://www.kotak.com/en/careers.html", "discovery_index"),
    ("sbi:careers", "https://sbi.co.in/web/careers", "discovery_index"),
    # ── 19. HFT / QUANT (EXTENDED, INTERNATIONAL) ────────────────────────────
    ("virtu:careers", "https://www.virtu.com/careers/", "discovery_index"),
    ("geneva-trading:careers", "https://www.genevatrading.com/careers", "discovery_index"),
    ("qube-rt:careers", "https://www.qube-rt.com/careers", "discovery_index"),
    ("wolverine-trading:careers", "https://www.wolve.com/careers", "discovery_index"),
    ("belvederetrading:careers", "https://www.belvederetrading.com/careers/", "discovery_index"),
    ("tradelink:careers", "https://www.tradelink.com/careers", "discovery_index"),
    ("headlandstech:careers", "https://www.headlandstech.com/careers", "discovery_index"),
    # ── 20. E-COMMERCE & RETAIL TECH (GLOBAL) ────────────────────────────────
    ("shopee:careers", "https://careers.shopee.com", "discovery_index"),
    ("lazada:careers", "https://www.lazada.com/careers/", "discovery_index"),
    ("mercadolibre:careers", "https://careers.mercadolibre.com", "discovery_index"),
    ("etsy:careers", "https://careers.etsy.com", "discovery_index"),
    ("chewy:careers", "https://careers.chewy.com", "discovery_index"),
    ("stitchfix:greenhouse", "https://boards.greenhouse.io/stitchfix", "official_ats"),
    ("thredup:greenhouse", "https://boards.greenhouse.io/thredup", "official_ats"),
    ("poshmark:greenhouse", "https://boards.greenhouse.io/poshmark", "official_ats"),
    ("depop:greenhouse", "https://boards.greenhouse.io/depop", "official_ats"),
    ("vinted:careers", "https://careers.vinted.com", "discovery_index"),
]


def get_all_registered_boards() -> list[tuple[str, str, str]]:
    """Returns the full master list of all verified seed boards."""
    return list(REGISTERED_BOARDS)


def get_discovery_index_sources() -> set[str]:
    """Returns set of source_ids that are categorized as discovery indexes."""
    return {
        source_id
        for source_id, _, source_type in REGISTERED_BOARDS
        if source_type == "discovery_index"
    }


async def verify_single_url(
    client: httpx.AsyncClient, item: tuple[str, str, str]
) -> tuple[bool, str, tuple[str, str, str]]:
    """Tests a single board URL for 200 OK status."""
    source_id, url, _ = item
    try:
        resp = await client.get(url, follow_redirects=True, timeout=10.0)
        if resp.status_code == 200:
            return True, f"HTTP {resp.status_code}", item
        return False, f"HTTP {resp.status_code}", item
    except Exception as exc:
        return False, str(exc), item


async def verify_board_registry(
    max_concurrency: int = 20,
) -> dict[str, Any]:
    """Asynchronously verifies 100% of registered boards for live 200 OK responses."""
    sem = asyncio.Semaphore(max_concurrency)
    valid_items: list[tuple[str, str, str]] = []
    failed_items: list[tuple[tuple[str, str, str], str]] = []

    async def _worker(client: httpx.AsyncClient, item: tuple[str, str, str]):
        async with sem:
            ok, reason, board = await verify_single_url(client, item)
            if ok:
                valid_items.append(board)
            else:
                failed_items.append((board, reason))

    client = await get_client("board_registry", timeout=15.0)
    tasks = [_worker(client, item) for item in REGISTERED_BOARDS]
    await asyncio.gather(*tasks)

    results = {
        "total": len(REGISTERED_BOARDS),
        "valid_count": len(valid_items),
        "failed_count": len(failed_items),
        "valid_boards": valid_items,
        "failed_boards": failed_items,
    }

    msg = f"Registry verified: {len(valid_items)}/{len(REGISTERED_BOARDS)} boards OK"
    logger.info(msg)
    return results
